worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    # ── Algoritmo 1: Round Robin ─────────────────────
    upstream backend_round_robin {
        server backend1:8000 max_fails=3 fail_timeout=10s;
        server backend2:8000 max_fails=3 fail_timeout=10s;
        server backend3:8000 max_fails=3 fail_timeout=10s;
    }

    # ── Algoritmo 2: Least Connections ──────────────
    upstream backend_least_conn {
        least_conn;
        server backend1:8000 max_fails=3 fail_timeout=10s;
        server backend2:8000 max_fails=3 fail_timeout=10s;
        server backend3:8000 max_fails=3 fail_timeout=10s;
    }

    # ── Algoritmo 3: IP Hash ─────────────────────────
    upstream backend_ip_hash {
        ip_hash;
        server backend1:8000 max_fails=3 fail_timeout=10s;
        server backend2:8000 max_fails=3 fail_timeout=10s;
        server backend3:8000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        # Métricas NGINX
        location /nginx_status {
            stub_status;
            allow all;
        }

        # API → FastAPI backends
        location /api/ {
            proxy_pass http://backend_round_robin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout      5s;
            proxy_read_timeout         10s;
            proxy_next_upstream        error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries  3;
        }

        # Frontend → React build
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
