worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    upstream backends {
        # Algoritmo activo: round-robin (default)
        # # # least_conn;
        # ip_hash;

        server backend1:3000 max_fails=3 fail_timeout=10s;
        server backend2:3000 max_fails=3 fail_timeout=10s;
        server backend3:3000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        location /nginx_status {
            stub_status;
            allow all;
        }

        location / {
            proxy_pass http://backends;
            proxy_connect_timeout      5s;
            proxy_read_timeout         10s;
            proxy_next_upstream        error timeout http_500;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
